# version: '3.8'

services:

  handler:
    build: ./handler
    ports:
      - 8081:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./handler:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./handler
    command: celery --app=workers.app worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./handler:/app
    environment:
      - CELERY_BROKER_URL="redis://redis:6379/0"
      - CELERY_RESULT_BACKEND="redis://redis:6379/0"
      - MODEL_PATH=""
    depends_on:
      - handler
      - redis

  redis:
    image: redis:6-alpine

  # dashboard:
  #   build: ./project
  #   command:  flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - web
  #     - redis
  #     - worker
