version: '3.8'

services:

  handler:
    build: ./handler
    ports:
      - 8081:8000
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./handler:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  worker:
    build: ./handler
    command: celery worker --app=app.workers.cel_app --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./handler:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:password@postgres:5432/results
    depends_on:
      - handler
      - redis
      - postgres

  redis:
    image: redis:6-alpine

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgres-data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: results

